### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by tn340bv**
update with curl command

### CODE REVIEW

**Comment by WadeBarnes** [comment]
Why do you need curl installed in the image?

**Comment by tn340bv** [comment]
While creating the docker image it failed because of curl command not found.

**Review by WadeBarnes — APPROVED** [review]

**Comment by tn340bv** [comment]
Hi Wade,

After deploying in the OpenShift. I’m facing the issue its not creating the persistenvolume.
Do we need to do anything additional steps .

Generated from persistentvolume-controller storageclass.storage.k8s.io "netapp-file-standard" not found

Thanks
Pavan

**Comment by WadeBarnes** [comment]
It's likely due to the fact that the `netapp-file-standard` storage class may not be available on your OpenShift cluster.  The configurations were turned to BC Gov clusters.
You can try setting the `*_PERSISTENT_VOLUME_CLASS` parameters to a storage class that is available on your cluster.  Or set the parameters to a blank string to use the default class.  Another option is to remove the `storageClassName` lines from your copy of the temple altogether.

**Pull request merged**
